// Code generated by hertz generator.

package demo

import (
	"context"

	demo "github.com/211250125/biz/model/demo"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMessage .
// @router /getMessage [GET]
func GetMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo.Response)

	c.JSON(consts.StatusOK, resp)
}
