// Code generated by hertz generator.

package teacher

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	teacher "github.com/njuer/course/cloudwego/httpsvr/biz/model/teacher"
)

// Register .
// @router /add-teacher-info [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req teacher.Teacher
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(teacher.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// Query .
// @router /query-teacher-info [GET]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req teacher.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(teacher.Teacher)

	c.JSON(consts.StatusOK, resp)
}
