// Code generated by hertz generator.

package student

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	student "github.com/njuer/course/cloudwego/httpsvr/biz/model/student"
)

// Register .
// @router /add-student-info [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(student.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// Query .
// @router /query-student-info [GET]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(student.Student)

	c.JSON(consts.StatusOK, resp)
}
