// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/211250125/biz/model/demo"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/kitex-examples/hello/kitex_gen/api/hello"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
	etcd "github.com/kitex-contrib/registry-etcd"
	"log"
)

type HelloImpl struct{}

func (h *HelloImpl) Echo(ctx context.Context, req *demo.Request) (resp *demo.Response, err error) {
	resp = &demo.Response{
		Message: "message",
	}
	return
}

func main() {
	r, err := etcd.NewEtcdRegistry([]string{"127.0.0.1:2379"})
	if err != nil {
		log.Fatal(err)
	}
	svr := hello.NewServer(new(HelloImpl), server.WithRegistry(r),
		server.WithServerBasicInfo(&rpcinfo.EndpointBasicInfo{
			ServiceName: "hello",
		}))

	err = svr.Run()
	if err != nil {
		log.Println(err.Error())
	}
	h := server.Default()

	register(h)
	h.Spin()
}
