// Code generated by hertz generator.

package demo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}
