// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/njuer/course/cloudwego/httpsvr/idlProvider"
	"github.com/njuer/course/cloudwego/httpsvr/kitexClientProvider"
)

func main() {
	h := server.Default()

	register(h)
	kitexClientProvider.Init()
	idlProvider.Init()
	h.Spin()
}
