// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/njuer/course/cloudwego/httpsvr/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/get/*getInfo", handler.Get)
	r.POST("/post/*postInfo", handler.Post)
}
